#!/bin/sh

set -e    # halt on first error

link=all  # link all binaries by default
linked=no # track whether we linked

case $1 in
  -nolink) link=none ; shift ;;  # don't link
  -link)   link="$2" ; shift ; shift ;;  # link only one binary
esac

CC=gcc

# compile and link against course software and netpbm library
CFLAGS="-I. -I/usr/local/cii/include -I/usr/local/include -I/csc/411/include"
LIBS="-lcii -lm"  
LFLAGS="-L/usr/local/cii/lib -L/usr/local/lib -L/csc/411/lib"

# these flags max out warnings and debug info
FLAGS="-no-pie -g -O1 -Wall -Wextra -Werror -Wfatal-errors -std=c99 -pedantic"

# compile each argument to a .o file
$CC $FLAGS $CFLAGS -c st_test.c

########### the middle part is different for each assignment
# link together .o files + libraries to make executable binaries
# using one case statement per executable binary
case $link in
    all|st) $CC $FLAGS $LFLAGS -o st st_test.o \
                    $LIBS
              linked=yes ;;
esac

# error if asked to link something we didn't recognize
if [ $linked = no ]; then
  case $link in  # if the -link option makes no sense, complain
    none) ;; # OK, do nothing
    *) echo "`basename $0`: don't know how to link $link" 1>&2 ; exit 1 ;;
  esac
fi

rm -f *.o  # make sure no object files are left hanging around
